[static_params]
; Sample parameters
sample_length = 64
sampling_rate = 2048
f_lower = 4
bandpass_lower = 4
bandpass_upper = 1024
; Noise parameters
correlation_below_freq = 10
correlation_alpha = 0.4
; Waveform parameters  IMRPhenomD SEOBNRv4
approximant = IMRPhenomD 
; Luminosity distance to the binary (in Mpc) 
spin1z = 0.998
spin2z = 0
distance = 100
nomf_snr = 10
fade_on_alpha = 0.25
num_mergers = 1
merger_time = 0.97
whiten_segment_duration = 2
whiten_max_filter_duration = 2

[variable_params]
mass1 = 
mass2 = 
inclination =
coa_phase =
# Antenna
right_ascension =
declination =
polarization =

[prior-mass1]  
; Prior for mass1
name = uniform
min-mass1 = 10
max-mass1 = 80

[prior-mass2]
; Prior for spin2z
name = uniform
min-mass2 = 10
max-mass2 = 80

[constraint-masses]
name = custom
constraint_arg = mass2 <= mass1

[prior-inclination]
name = sin_angle

[prior-coa_phase]
; Coalescence phase prior
name = uniform_angle

[prior-declination+right_ascension]
; Sky position prior
name = uniform_solidangle
polar-angle = declination
azimuthal-angle = right_ascension

[prior-polarization]
; Polarization prior
name = uniform_angle